heroes:
  - name: 'Rondriane'
    wt: 8
    ar: 5
    hp: 5
    at: 18
    pa: 17
  - name: 'Alrik'
    wt: 5
    ar: 2
    hp: 2
    at: 12
    pa: 12
  - name: 'Rumpo'
    wt: 3
    ar: 0
    hp: 3
    at: 5
    pa: 4
